<?php 
/**
 * ThemesDepot Framework theme options and page options
 *
 * @package ThemesDepot Framework
 */

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_brand-options',
		'title' => 'Brand Options',
		'fields' => array (
			array (
				'key' => 'field_528bd8c410a3c',
				'label' => 'Add Brand Image',
				'name' => 'add_brand_image',
				'type' => 'image',
				'instructions' => 'If needed you can add a brand image here. This image will be used into the "Brands Carousel" available in many parts of the theme.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'vehicle_model',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_insert-video',
		'title' => 'Insert Video',
		'fields' => array (
			array (
				'key' => 'field_526e89ff8873d',
				'label' => 'Post Video',
				'name' => 'post_video',
				'type' => 'textarea',
				'instructions' => 'Insert the video embed code here.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'html',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'video',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_page-layout',
		'title' => 'Page Layout',
		'fields' => array (
			array (
				'key' => 'field_526fb62870650',
				'label' => 'Page Layout',
				'name' => 'page_layout',
				'type' => 'select',
				'instructions' => 'Select the layout of this page.',
				'choices' => array (
					'Fullwidth' => 'Fullwidth',
					'Right Side Sidebar' => 'Right Side Sidebar',
					'Left Side Sidebar' => 'Left Side Sidebar',
				),
				'default_value' => 'Right Side Sidebar',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52af2da4691d2',
				'label' => 'Remove SubHeader Spacing',
				'name' => 'remove_subheader_spacing',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to remove the spacing after the subheader.',
				'message' => 'Remove SubHeader Spacing',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 1,
				),
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-dashboard.php',
					'order_no' => 1,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_post-gallery',
		'title' => 'Post Gallery',
		'fields' => array (
			array (
				'key' => 'field_526d104df0ce7',
				'label' => 'Images Gallery',
				'name' => 'images_gallery',
				'type' => 'gallery',
				'instructions' => 'Upload images here for the gallery.',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'gallery',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_post-link-settings',
		'title' => 'Post Link Settings',
		'fields' => array (
			array (
				'key' => 'field_526e90679aaf1',
				'label' => 'Link',
				'name' => 'link',
				'type' => 'text',
				'instructions' => 'Enter the url of the link',
				'default_value' => 'http://',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_526e907b9aaf2',
				'label' => 'Link Label',
				'name' => 'link_label',
				'type' => 'text',
				'instructions' => 'Enter the label url if needed.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'link',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_quote-settings',
		'title' => 'Quote Settings',
		'fields' => array (
			array (
				'key' => 'field_526e8dc34d51b',
				'label' => 'Insert Quote',
				'name' => 'insert_quote',
				'type' => 'textarea',
				'instructions' => 'Insert the quote here.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_526e8dd44d51c',
				'label' => 'Quote Author',
				'name' => 'quote_author',
				'type' => 'text',
				'instructions' => 'Enter the author of the quote.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'quote',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_search-theme-settings',
		'title' => 'Search Theme Settings',
		'fields' => array (
			array (
				'key' => 'field_528e1ae61c369',
				'label' => 'Main Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_528e1af81c36a',
				'label' => 'Search Results Page',
				'name' => 'search_results_page',
				'type' => 'page_link',
				'instructions' => 'Select the page that has the "Search Results" page template applied. If you don\'t have a search results page, you must create it for the search form to work.',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_528e1b111c36b',
				'label' => 'Results Per Page',
				'name' => 'results_per_page',
				'type' => 'number',
				'instructions' => 'Select how many results you\'d like to display per page.',
				'default_value' => 15,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_528e2b59f2a5e',
				'label' => 'Display Price Filter',
				'name' => 'display_price_filter',
				'type' => 'true_false',
				'instructions' => 'Select if you want to enable this field or not for the search vehicles widget.',
				'message' => 'Display Price Filter',
				'default_value' => 1,
			),
			array (
				'key' => 'field_528e1bec3909f',
				'label' => 'Display Advanced Search Form In Taxonomy',
				'name' => 'display_advanced_search_form_in_taxonomy',
				'type' => 'true_false',
				'instructions' => 'Enable/Disable the advanced search form in taxonomy pages.',
				'message' => 'Display Advanced Search Form In Taxonomy',
				'default_value' => 1,
			),
			array (
				'key' => 'field_528e1d01390a0',
				'label' => 'Display Advanced Search Form In Search Results',
				'name' => 'display_advanced_search_form_in_search',
				'type' => 'true_false',
				'instructions' => 'Enable/Disable the advanced search form on the search results page.',
				'message' => 'Display Advanced Search Form In Search Results',
				'default_value' => 1,
			),
			array (
				'key' => 'field_528f8d11650e4',
				'label' => 'Display Carousel In Search Results Page',
				'name' => 'display_carousel_in_search_results_page',
				'type' => 'select',
				'instructions' => 'Select if you wish to display a carousel into your search results page.',
				'choices' => array (
					'Disable Carousel' => 'Disable Carousel',
					'Display Latest Vehicles Carousel' => 'Display Latest Vehicles Carousel',
					'Display Featured Vehicles Carousel' => 'Display Featured Vehicles Carousel',
				),
				'default_value' => 'Disable Carousel',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_528f8f9437250',
				'label' => 'Display Brands List In Search Results',
				'name' => 'display_brands_list_in_search_results',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the brand list into your search results.',
				'message' => 'Display Brands List In Search Results',
				'default_value' => 0,
			),
			array (
				'key' => 'field_528e1df20f829',
				'label' => 'Price Filter Setup',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_528e1e010f82a',
				'label' => 'About Search Filter',
				'name' => '',
				'type' => 'message',
				'message' => '<h1>About The Search Filter:</h1>
	<p>The vehicles search form comes with a price range filter which allows you and your users to define a range within which you want to search for vehicles. Being a powerful tool, it comes with a few settings that you must fill and select here, in order to make it work as it should.</p>',
			),
			array (
				'key' => 'field_528e2011ca85e',
				'label' => 'Minimum Value',
				'name' => 'minimum_value',
				'type' => 'number',
				'instructions' => 'Set the base value of range. (From where the range should start)',
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_528e2099ca85f',
				'label' => 'Maximum Value',
				'name' => 'maximum_value',
				'type' => 'number',
				'instructions' => 'Set the maximum value of range. (The End Point Of The Range)',
				'default_value' => 80000,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_528e20ecca860',
				'label' => 'Step Value',
				'name' => 'step_value',
				'type' => 'number',
				'instructions' => 'Set the step value of the range. This is the amount that increases/decreases every time you move the range point.',
				'default_value' => 1000,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_528e53a1d4036',
				'label' => 'Mileage Filter Setup',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_528e53add4037',
				'label' => 'About Mileage Filter',
				'name' => '',
				'type' => 'message',
				'message' => '<h1>About The Mileage Filter:</h1>
	<p>The vehicles search form comes with a mileage range filter which allows you and your users to define a range within which you want to search for vehicles. Being a powerful tool, it comes with a few settings that you must fill and select here, in order to make it work as it should.</p>',
			),
			array (
				'key' => 'field_528e5521d4038',
				'label' => 'Mileage Minimum Value',
				'name' => 'mileage_minimum_value',
				'type' => 'number',
				'instructions' => 'Set the base value of range. (From where the range should start)',
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_528e5526d4039',
				'label' => 'Mileage Maximum Value',
				'name' => 'mileage_maximum_value',
				'type' => 'number',
				'instructions' => 'Set the maximum value of range. (The End Point Of The Range)',
				'default_value' => 300000,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_528e554fd403a',
				'label' => 'Mileage Step Value',
				'name' => 'mileage_step_value',
				'type' => 'number',
				'instructions' => 'Set the step value of the range. This is the amount that increases/decreases every time you move the range point.',
				'default_value' => 1000,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-search-setup',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_skin-customization',
		'title' => 'Skin Customization',
		'fields' => array (
			array (
				'key' => 'field_52cbf7717f49f',
				'label' => 'General Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_52d58e42694c7',
				'label' => 'Enable Front-End Demo Style Switcher',
				'name' => 'enable_front_end_demo_style_switcher',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the frontend demo style switcher.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_52cbf77b7f4a0',
				'label' => 'Enable Custom Skin',
				'name' => 'enable_custom_skin',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to customize each color of the skin.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_52cbf79b7f4a1',
				'label' => 'Primary Color',
				'name' => 'primary_color',
				'type' => 'color_picker',
				'default_value' => '#1A86CA',
			),
			array (
				'key' => 'field_52cbf7bd7f4a2',
				'label' => 'Secondary Color',
				'name' => 'secondary_color',
				'type' => 'color_picker',
				'default_value' => '#fec31d',
			),
			array (
				'key' => 'field_52cbf7d47f4a3',
				'label' => 'Alternative Color',
				'name' => 'alternative_color',
				'type' => 'color_picker',
				'default_value' => '#999',
			),
			array (
				'key' => 'field_52cbfbccc6dd0',
				'label' => 'General Headings',
				'name' => 'general_headings',
				'type' => 'color_picker',
				'default_value' => '#212121',
			),
			array (
				'key' => 'field_52cbf6d47f49a',
				'label' => 'Header',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_52cbf6e17f49b',
				'label' => 'Top Bar Background',
				'name' => 'top_bar_background',
				'type' => 'color_picker',
				'default_value' => '#222',
			),
			array (
				'key' => 'field_52cbf7177f49c',
				'label' => 'Top Bar Bottom Border Color',
				'name' => 'top_bar_bottom_border_color',
				'type' => 'color_picker',
				'default_value' => '#3f3f3f',
			),
			array (
				'key' => 'field_52cbf73c7f49d',
				'label' => 'Top Bar Text Color',
				'name' => 'top_bar_text_color',
				'type' => 'color_picker',
				'default_value' => '#a7a7a7',
			),
			array (
				'key' => 'field_52cbf7547f49e',
				'label' => 'Top Bar Link Color',
				'name' => 'top_bar_link_color',
				'type' => 'color_picker',
				'default_value' => '#fff',
			),
			array (
				'key' => 'field_52cbf81bc6dc0',
				'label' => 'Header Background Gradient Start Color',
				'name' => 'header_background_gradient_start_color',
				'type' => 'color_picker',
				'default_value' => '#16181A',
			),
			array (
				'key' => 'field_52cbf83bc6dc1',
				'label' => 'Header Background Gradient End Color',
				'name' => 'header_background_gradient_end_color',
				'type' => 'color_picker',
				'default_value' => '#333',
			),
			array (
				'key' => 'field_52cbf96ec6dc2',
				'label' => 'Navigation Menu Links Color',
				'name' => 'navigation_menu_links_color',
				'type' => 'color_picker',
				'default_value' => '#DADADA',
			),
			array (
				'key' => 'field_52cbf992c6dc3',
				'label' => 'SubMenu	Background Color',
				'name' => 'submenu__background_color',
				'type' => 'color_picker',
				'default_value' => '#1F1F1F',
			),
			array (
				'key' => 'field_52cbf9e2c6dc4',
				'label' => 'Page Content',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_52cbfa4fc6dc7',
				'label' => 'Page Background Color',
				'name' => 'page_background_color',
				'type' => 'color_picker',
				'default_value' => '#fff',
			),
			array (
				'key' => 'field_52cbfa06c6dc5',
				'label' => 'Headings Color',
				'name' => 'headings_color',
				'type' => 'color_picker',
				'default_value' => '#444444',
			),
			array (
				'key' => 'field_52cbfa1dc6dc6',
				'label' => 'Paragraphs and text color',
				'name' => 'paragraphs_and_text_color',
				'type' => 'color_picker',
				'default_value' => '#555',
			),
			array (
				'key' => 'field_52cbfa86c6dc8',
				'label' => 'Posts Title Color',
				'name' => 'posts_title_color',
				'type' => 'color_picker',
				'default_value' => '#212121',
			),
			array (
				'key' => 'field_52cbfab7c6dc9',
				'label' => 'Widget Titles Color',
				'name' => 'widget_titles_color',
				'type' => 'color_picker',
				'default_value' => '#444444',
			),
			array (
				'key' => 'field_52cbfaf7c6dca',
				'label' => 'Widget Title Border Color',
				'name' => 'widget_title_border_color',
				'type' => 'color_picker',
				'default_value' => '#cccccc',
			),
			array (
				'key' => 'field_52cbfb03c6dcb',
				'label' => 'Widget Title Border Highlight Color',
				'name' => 'widget_title_border_highlight_color',
				'type' => 'color_picker',
				'default_value' => '#f1f1f1',
			),
			array (
				'key' => 'field_52cbfb30c6dcc',
				'label' => 'Sidebar Text Color',
				'name' => 'sidebar_text_color',
				'type' => 'color_picker',
				'default_value' => '#888888',
			),
			array (
				'key' => 'field_52cbfb4ec6dcd',
				'label' => 'Vehicles',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_52cbfb7cc6dce',
				'label' => 'Featured Vehicles Top Highlight Background Color',
				'name' => 'featured_vehicles_top_highlight_background_color',
				'type' => 'color_picker',
				'default_value' => '#F7F7F7',
			),
			array (
				'key' => 'field_52cbfba7c6dcf',
				'label' => 'Featured Vehicles Top Highlight Border',
				'name' => 'featured_vehicles_top_highlight_border',
				'type' => 'color_picker',
				'default_value' => '#ECECEC',
			),
			array (
				'key' => 'field_52cbfc38c6dd1',
				'label' => 'Vehicles Top Bar Background',
				'name' => 'vehicles_top_bar_background',
				'type' => 'color_picker',
				'default_value' => '#FAFAFA',
			),
			array (
				'key' => 'field_52cbfc5bc6dd2',
				'label' => 'Vehicles Top Bar Border',
				'name' => 'vehicles_top_bar_border',
				'type' => 'color_picker',
				'default_value' => '#ECECEC',
			),
			array (
				'key' => 'field_52cbfc7ec6dd3',
				'label' => 'Vehicles Carousel Background',
				'name' => 'vehicles_carousel_background',
				'type' => 'color_picker',
				'default_value' => '#303C4B',
			),
			array (
				'key' => 'field_52cbfc99c6dd4',
				'label' => 'Vehicles Carousel Top Border',
				'name' => 'vehicles_carousel_top_border',
				'type' => 'color_picker',
				'default_value' => '#D1D1D1',
			),
			array (
				'key' => 'field_52cbfcaec6dd5',
				'label' => 'Vehicles Carousel Border Bottom',
				'name' => 'vehicles_carousel_border_bottom',
				'type' => 'color_picker',
				'default_value' => '#4E4E4E',
			),
			array (
				'key' => 'field_52cbfccfc6dd6',
				'label' => 'Vehicles Carousel Sign Up Link Color',
				'name' => 'vehicles_carousel_sign_up_link_color',
				'type' => 'color_picker',
				'default_value' => '#96aabc',
			),
			array (
				'key' => 'field_52cbfcf9c6dd7',
				'label' => 'Vehicles Carousel Link Color',
				'name' => 'vehicles_carousel_link_color',
				'type' => 'color_picker',
				'default_value' => '#fff',
			),
			array (
				'key' => 'field_52cbfd0ec6dd8',
				'label' => 'Vehicles Carousel Date Color',
				'name' => 'vehicles_carousel_date_color',
				'type' => 'color_picker',
				'default_value' => '#96aabc',
			),
			array (
				'key' => 'field_52cbfd21c6dd9',
				'label' => 'Vehicles Carousel Read More Color',
				'name' => 'vehicles_carousel_read_more_color',
				'type' => 'color_picker',
				'default_value' => '#03b4ea',
			),
			array (
				'key' => 'field_52cbfd7ae357b',
				'label' => 'Footer',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_52cbfd82e357c',
				'label' => 'Pre Footer Background',
				'name' => 'pre_footer_background',
				'type' => 'color_picker',
				'default_value' => '#fafafa',
			),
			array (
				'key' => 'field_52cbfd9ee357d',
				'label' => 'Pre Footer Top Border',
				'name' => 'pre_footer_top_border',
				'type' => 'color_picker',
				'default_value' => '#dfdfdf',
			),
			array (
				'key' => 'field_52cbfdb2e357e',
				'label' => 'Pre Footer Links Color',
				'name' => 'pre_footer_links_color',
				'type' => 'color_picker',
				'default_value' => '#7e848e',
			),
			array (
				'key' => 'field_52cbfdc9e357f',
				'label' => 'Pre Footer Text Color',
				'name' => 'pre_footer_text_color',
				'type' => 'color_picker',
				'default_value' => '#7e848e',
			),
			array (
				'key' => 'field_52cbfde1e3580',
				'label' => 'Pre Footer Widget Titles',
				'name' => 'pre_footer_widget_titles',
				'type' => 'color_picker',
				'default_value' => '#282c32',
			),
			array (
				'key' => 'field_52cbfdefe3581',
				'label' => 'Main Footer Background Color',
				'name' => 'main_footer_background_color',
				'type' => 'color_picker',
				'default_value' => '#26282a',
			),
			array (
				'key' => 'field_52cbfe11e3582',
				'label' => 'Main Footer Text Color',
				'name' => 'main_footer_text_color',
				'type' => 'color_picker',
				'default_value' => '#a7a7a7',
			),
			array (
				'key' => 'field_52cbfe52e3583',
				'label' => 'Main Footer Info Area Headings',
				'name' => 'main_footer_info_area_headings',
				'type' => 'color_picker',
				'default_value' => '#9b9b9b',
			),
			array (
				'key' => 'field_52cbfe6fe3584',
				'label' => 'Main Footer Info Area Stats Color',
				'name' => 'main_footer_info_area_stats_color',
				'type' => 'color_picker',
				'default_value' => '#fff',
			),
			array (
				'key' => 'field_52cbfe8ee3585',
				'label' => 'Main Footer Info Area Button Text Color',
				'name' => 'main_footer_info_area_button_text_color',
				'type' => 'color_picker',
				'default_value' => '#222',
			),
			array (
				'key' => 'field_52cc22804acfd',
				'label' => 'Main Footer Widget Titles',
				'name' => 'main_footer_widget_titles',
				'type' => 'color_picker',
				'default_value' => '#fff',
			),
			array (
				'key' => 'field_52cc22ba4acfe',
				'label' => 'Main Footer Stats Column Background',
				'name' => 'main_footer_stats_column_background',
				'type' => 'color_picker',
				'default_value' => '#3C3C3C',
			),
			array (
				'key' => 'field_52cc22d84acff',
				'label' => 'Main Footer Stats Column Border',
				'name' => 'main_footer_stats_column_border',
				'type' => 'color_picker',
				'default_value' => '#555',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-skin-customization',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_theme-options',
		'title' => 'Theme Options',
		'fields' => array (
			array (
				'key' => 'field_52642cd548bcd',
				'label' => 'General Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_526911e7cf49b',
				'label' => 'Custom Logo',
				'name' => 'custom_logo',
				'type' => 'image',
				'instructions' => 'Upload your custom logo here.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_52642db148bcf',
				'label' => 'Custom Favicon',
				'name' => 'custom_favicon',
				'type' => 'image',
				'instructions' => 'Upload Your Custom Favicon Here.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_526fb4787384e',
				'label' => 'Disable Comments On Pages',
				'name' => 'disable_comments_on_pages',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to disable comments on pages.',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_526522eb3d7cb',
				'label' => 'Social Networks',
				'name' => 'social_networks',
				'type' => 'repeater',
				'instructions' => 'Add your social networks here.',
				'sub_fields' => array (
					array (
						'key' => 'field_5265232a3d7cd',
						'label' => 'Social Network Icon',
						'name' => 'social_network_icon',
						'type' => 'text',
						'instructions' => 'Enter the icon code of the icon that you would like to use. The full list of icons can be found on the live demo or into the "icon-list" folder that comes with the full package that you download from themeforest.',
						'column_width' => '',
						'default_value' => 'icon-facebook',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5265236a3d7ce',
						'label' => 'Social Network Url',
						'name' => 'social_network_url',
						'type' => 'text',
						'instructions' => 'Enter the url of your profile',
						'column_width' => '',
						'default_value' => 'http://',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Social Network',
			),
			array (
				'key' => 'field_528f913bc8669',
				'label' => 'All Brands Page',
				'name' => 'all_brands_page',
				'type' => 'page_link',
				'instructions' => 'Select the page with the "All Brands" page template applied, this is needed to link to this page from the button into the "brands list".',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5283ce94bbshi',
				'label' => 'Disable Shipping Information On Checkout',
				'name' => 'display_shipping',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to disable the shipping box at checkout.',
				'message' => 'Disable Shipping Information On Checkout',
				'default_value' => 1,
			),
			array (
				'key' => 'field_5283ce94bbrtl',
				'label' => 'Enable RTL Stylesheet',
				'name' => 'enable_rtl',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to enable the stylesheet for RTL languages.',
				'message' => 'Enable RTL Stylesheet',
				'default_value' => 0,
			),
			array (
				'key' => 'field_526995ae82eeb',
				'label' => 'Typography',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_52642deec9c9d',
				'label' => 'Google Font Url',
				'name' => 'google_font_url',
				'type' => 'text',
				'instructions' => 'Enter The Google Font Url Here.',
				'default_value' => 'fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52642e4bc9c9e',
				'label' => 'Google Font Name',
				'name' => 'google_font_name',
				'type' => 'text',
				'instructions' => 'Enter The Font Family Name Of The Font.',
				'default_value' => 'Open Sans',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_526995c382eec',
				'label' => 'Google Font Url (Headings)',
				'name' => 'google_font_url_headings',
				'type' => 'text',
				'instructions' => 'Enter The Google Font Url Here. This font will be used for headings and other important text inside the theme.',
				'default_value' => 'fonts.googleapis.com/css?family=Montserrat:400,700',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5269960e82eed',
				'label' => 'Google Font Name (Headings)',
				'name' => 'google_font_name_headings',
				'type' => 'text',
				'instructions' => 'Enter the name of the font used for headings.',
				'default_value' => 'Montserrat',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52642f571b01e',
				'label' => 'Header Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_52642f6a1b01f',
				'label' => 'Display Top Bar',
				'name' => 'display_top_bar',
				'type' => 'true_false',
				'instructions' => 'Select If You Wish To Display The Header Topbar.',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_5269465f0db30',
				'label' => 'Top Bar Visitors Message',
				'name' => 'top_bar_visitors_content',
				'type' => 'wysiwyg',
				'instructions' => 'Set the message that should be displayed when a visitor visits your website.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52642f6a1b01f',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'AutoDealer is the premier destination to buy & sell vehicles. Sign up now »',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5283ce94bb5b6',
				'label' => 'Display Profile Link In Top Bar',
				'name' => 'display_profile_link_in_top_bar',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the profile link inside the topbar.',
				'message' => 'Display Profile Link In Top Bar',
				'default_value' => 1,
			),
			array (
				'key' => 'field_52642fe59d4cc',
				'label' => 'Footer Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_52b06cb3cd371',
				'label' => 'Enable Additional Footer',
				'name' => 'enable_additional_footer',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display an additional footer on top of the main footer.',
				'message' => 'Enable Additional Footer',
				'default_value' => 1,
			),
			array (
				'key' => 'field_52b06cdfcd372',
				'label' => 'Additional Footer Widgetized Columns',
				'name' => 'additional_footer_widgetized_columns',
				'type' => 'select',
				'instructions' => 'Select How Many Columns Your Additional Footer Should Have.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52b06cb3cd371',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					4 => 4,
					3 => 3,
					2 => 2,
				),
				'default_value' => 4,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52b0799ba1160',
				'label' => 'Enable Stats Column',
				'name' => 'enable_stats_column',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the stats column into the footer',
				'message' => 'Enable Stats Column',
				'default_value' => 1,
			),
			array (
				'key' => 'field_52b08c529ddfb',
				'label' => 'Stats Column Content',
				'name' => 'stats_column_content',
				'type' => 'wysiwyg',
				'instructions' => 'Here you can customize the content of the stats column and display various content. Use the available tags to replace the content with actual stats.
	<pre>
	%total_vehicles% = displays the total amount of submitted vehicles
	%total_users% = displays the total amount of registered users on your website
	%submit% = displays the submit vehicle page button
	</pre>',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52b0799ba1160',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '<h3>Total Vehicles On Sale</h3>
	%total_vehicles%
	
	<h3>Registered Users</h3>
	%total_users%
	
	<h3>Ready To Sell?</h3>
	%submit%',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_52642ff09d4cd',
				'label' => 'Widgetized Columns',
				'name' => 'widgetized_columns',
				'type' => 'select',
				'instructions' => 'Select How Many Columns Your Footer Should Have.',
				'choices' => array (
					4 => 4,
					3 => 3,
					2 => 2,
				),
				'default_value' => 4,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5264301a9d4ce',
				'label' => 'Copyright Text',
				'name' => 'copyright_text',
				'type' => 'wysiwyg',
				'instructions' => 'Enter Copyright Text Here',
				'default_value' => 'Copyright © 2013. Developed By <a href="#">ThemesDepot</a> & Powered By <a href="#">WordPress</a> - Hosted By <a href="http://www.eleven2.com/2582.html">Eleven2</a>',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_52696d8177322',
				'label' => 'Blog Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_526fb84787fd0',
				'label' => 'Enable Author Box',
				'name' => 'enable_author_box',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the author box in posts.',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_526fb86887fd1',
				'label' => 'Enable Social Sharing Buttons',
				'name' => 'enable_social_sharing_buttons',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display social sharing buttons.',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_52696d8c77323',
				'label' => 'Blog Header Content',
				'name' => 'blog_header_content',
				'type' => 'radio',
				'instructions' => 'Set the content of the header for the blog',
				'choices' => array (
					'Title Only' => 'Title Only',
					'Title With Subtitle' => 'Title With Subtitle',
					'Custom Content' => 'Custom Content',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'Title Only',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_52696fcb77324',
				'label' => 'Blog Title',
				'name' => 'blog_title',
				'type' => 'text',
				'instructions' => 'Enter the title that you would like to display',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52696d8c77323',
							'operator' => '!=',
							'value' => 'Custom Content',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'Latest News',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52696ff077325',
				'label' => 'Blog Subtitle',
				'name' => 'blog_subtitle',
				'type' => 'text',
				'instructions' => 'Enter the subtitle that you\'d like to display below the title of the blog.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52696d8c77323',
							'operator' => '==',
							'value' => 'Title With Subtitle',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'We Obsessively Cover The Latest Auto News',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5269701577326',
				'label' => 'Blog Custom Content',
				'name' => 'blog_custom_content',
				'type' => 'wysiwyg',
				'instructions' => 'Enter the content that you\'d like to display in the header.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52696d8c77323',
							'operator' => '==',
							'value' => 'Custom Content',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_526bd46e29f0d',
				'label' => 'Blog Layout',
				'name' => 'blog_layout',
				'type' => 'radio',
				'instructions' => 'Select the layout style of the blog',
				'choices' => array (
					'Classic Style' => 'Classic Style',
					'Mini Style' => 'Mini Style',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'Classic Style',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_526bdc3a2a068',
				'label' => 'Blog Sidebar Position',
				'name' => 'blog_sidebar_position',
				'type' => 'radio',
				'instructions' => 'Select the position of the sidebar.',
				'choices' => array (
					'Right Side' => 'Right Side',
					'Left Side' => 'Left Side',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_52698cf2de12d',
				'label' => 'Header Custom Background Color',
				'name' => 'header_custom_background_color',
				'type' => 'color_picker',
				'instructions' => 'If needed you can set a custom color for the header background.',
				'default_value' => '#2d3e52',
			),
			array (
				'key' => 'field_52698d37de12e',
				'label' => 'Header Custom Background Image',
				'name' => 'header_custom_background_image',
				'type' => 'image',
				'instructions' => 'If needed you can set a custom background image for the header background.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_52698d63de12f',
				'label' => 'Header Custom Background Image Overlay',
				'name' => 'header_custom_background_image_overlay',
				'type' => 'color_picker',
				'instructions' => 'If you want, you can add a semi transparent overlay background on top of the image.',
				'default_value' => '#2d3e52',
			),
			array (
				'key' => 'field_52c16d17faa7d',
				'label' => 'Homepage',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_52c9da16b568b',
				'label' => 'Homepage With Slider Setup',
				'name' => '',
				'type' => 'message',
				'message' => '<h1>Homepage With Slider Setup</h1>
	<h2>Use the following section to configure the "Homepage With Slider Setup" page template.</h2>',
			),
			array (
				'key' => 'field_52c9da2ab568c',
				'label' => 'Slider Shortcode',
				'name' => 'slider_shortcode',
				'type' => 'text',
				'instructions' => 'Enter the shortcode provided by the LayerSlider plugin or any other kind of slider. The slider will be displayed at the top of the page.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52c16d61faa7f',
				'label' => 'Homepage With Search Form Setup',
				'name' => '',
				'type' => 'message',
				'message' => '<h1>Homepage With Search Form Setup</h1>
	<h2>Use the following section to configure the "Homepage With Search Form" page template.</h2>',
			),
			array (
				'key' => 'field_52c16dd4204e3',
				'label' => 'Add Landing Image?',
				'name' => 'add_landing_image',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to use an image has background into the landing top area of the page. This image will be displayed as background underneath the search form.',
				'message' => 'Add Landing Image?',
				'default_value' => 0,
			),
			array (
				'key' => 'field_52c16e1f204e4',
				'label' => 'Upload Landing Image',
				'name' => 'upload_landing_image',
				'type' => 'image',
				'instructions' => 'Upload the landing image here.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52c16dd4204e3',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_52c17116204e5',
				'label' => 'Enable Overlay?',
				'name' => 'enable_overlay',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to add a transparent overlay above the background image.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52c16dd4204e3',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'message' => 'Enable Overlay?',
				'default_value' => 0,
			),
			array (
				'key' => 'field_52c1714a204e6',
				'label' => 'Overlay Color',
				'name' => 'overlay_color',
				'type' => 'color_picker',
				'instructions' => 'Set the color of the overlay',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52c17116204e5',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '#000',
			),
			array (
				'key' => 'field_52c1717e204e7',
				'label' => 'Form Area Background',
				'name' => 'form_area_background',
				'type' => 'color_picker',
				'instructions' => 'Select the color of the background for the form area. This background will be displayed only if you are not using an image as background.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_52c16dd4204e3',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '#000',
			),
			array (
				'key' => 'field_52c196be0496e',
				'label' => 'Search Form Tagline',
				'name' => 'search_form_tagline',
				'type' => 'wysiwyg',
				'instructions' => 'Enter the tagline that will be displayed above the search form. Please note that shortcodes aren\'t allowed here.',
				'default_value' => '<h1>Buy your new car on AutoDealer</h1>
	<h2>Everything you need to build an amazing dealership website</h2>',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-theme-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_user-dashboard-profile-settings',
		'title' => 'User Dashboard & Profile Settings',
		'fields' => array (
			array (
				'key' => 'field_5297d33da3513',
				'label' => 'Main Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5297d348a3514',
				'label' => 'Dashboard Page',
				'name' => 'dashboard_page',
				'type' => 'page_link',
				'instructions' => 'Select the page with the "User Dashboard" Page Template Applied. This is needed for theme to link to the dashboard page.',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_529e2a5861008',
				'label' => 'Dashboard Header Text',
				'name' => 'dashboard_header_text',
				'type' => 'textarea',
				'instructions' => 'Use this field to display some custom text for the dashboard. This text will be displayed next to the avatar.',
				'default_value' => 'Here you can have an overview of your vehicles on sale and customize your profile.',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_529f1d1348327',
				'label' => 'Edit Profile Page',
				'name' => 'edit_profile_page',
				'type' => 'page_link',
				'instructions' => 'Select the page with the "Edit Profile" page template applied, this is needed so the theme knows where this page is.',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_529f1d4648328',
				'label' => 'Edit Profile Header Text',
				'name' => 'edit_profile_header_text',
				'type' => 'textarea',
				'instructions' => 'Use this field to display some custom text for the edit profile page. This text will be displayed next to the avatar.',
				'default_value' => 'Here you can modify your profile details.',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5297d348a3ccc',
				'label' => 'Edit Vehicle Page',
				'name' => 'edit_vehicle_page',
				'type' => 'page_link',
				'instructions' => 'Select the page with the "Edit Vehicle" Page Template Applied. This is needed for theme to link to the dashboard page.',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52b3402755abe',
				'label' => 'Dealer Profile',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_52b3403055abf',
				'label' => 'Dealer Profile Page',
				'name' => 'dealer_profile_page',
				'type' => 'page_link',
				'instructions' => 'Select the page with the page template "Dealer Profile" this is needed for the dealer page to work.',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52b356fb520f9',
				'label' => 'Display Profile Info Bar',
				'name' => 'display_profile_info_bar',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the profile infobar into the dealer profile page. The infobar it that little gray bar that displays user registration date and total amount of submitted vehicles.',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_52b429cd573fd',
				'label' => 'Display Profile Information',
				'name' => 'display_profile_information',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display dealers information into their profile page.',
				'message' => '',
				'default_value' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-user-dashboard',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_vehicle-options',
		'title' => 'Vehicle Options',
		'fields' => array (
			array (
				'key' => 'field_5284ce9e21fa2',
				'label' => __('Vehicle Details','framework'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_533c029127838',
				'label' => __('Listing Title','framework'),
				'name' => 'listing_title',
				'type' => 'text',
				'instructions' => __('Enter the title of your advert.','framework'),
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_533c02a827839',
				'label' => __('Listing Description','framework'),
				'name' => 'listing_description',
				'type' => 'wysiwyg',
				'instructions' => __('Enter the description of your advert.','framework'),
				'required' => 1,
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_52892d5416d75',
				'label' => 'Set Vehicle As Featured',
				'name' => 'set_vehicle_as_featured',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to set this vehicle as featured. Featured vehicles are highlighted and are displayed at the top of the list.',
				'message' => 'Set Vehicle As Featured',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5284ceac21fa3',
				'label' => __('Price','framework'),
				'name' => 'price',
				'type' => 'text',
				'instructions' => __('Enter the vehicle price without the currency symbol.','framework'),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5284cf9721fa8',
				'label' => __('Discount %','framework'),
				'name' => 'discount',
				'type' => 'text',
				'instructions' => __('Select the discount % from the initial price. Note that the discount is not applied automatically, you\'ll have to input the price already discounted in the Price field','framework'),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5284d114beoth',
				'label' => __('Other Details','framework'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5285291966a70',
				'label' => __('Vehicle Position','framework'),
				'name' => 'vehicle_position',
				'type' => 'location-field',
				'instructions' => __('Set the address of the vehicle','framework'),
				'val' => 'address',
				'center' => '48.856614,2.3522219000000177',
				'zoom' => 16,
				'scrollwheel' => 1,
			),
			array (
				'key' => 'field_5284cf0d21fa4',
				'label' => __('Mileage','framework'),
				'name' => 'mileage',
				'type' => 'text',
				'instructions' => __('Number of kilometers. Ex: 100000. <span class="admin-desc">Symbol for kilometers is set into the Theme Options Panel</span>','framework'),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5284cf4b21fa5',
				'label' => __('Capacity','framework'),
				'name' => 'capacity',
				'type' => 'text',
				'instructions' => __('Motor capacity. Ex: 3200. <span class="admin-desc">Symbol for motor capacity is set into the theme options panel.</span>','framework'),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5284cf7121fa6',
				'label' => __('Power BHP','framework'),
				'name' => 'power_bhp',
				'type' => 'text',
				'instructions' => __('Motor Power in BHP','framework'),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5284cf8221fa7',
				'label' => __('Power KW','framework'),
				'name' => 'power_kw',
				'type' => 'text',
				'instructions' => __('Motor Power in KW','framework'),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			
			array (
				'key' => 'field_5284cfc421fa9',
				'label' => __('Consumption MPG','framework'),
				'name' => 'consumption_mpg',
				'type' => 'text',
				'instructions' => __('Consumption to 100 km, consumption symbol is set into the theme options panel.','framework'),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5284cfeb21faa',
				'label' => __('Emission Class','framework'),
				'name' => 'emission_class',
				'type' => 'text',
				'instructions' => __('Emission Class Ex: EURO 5 (428 g/KM)','framework'),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_528b42148d00d',
				'label' => __('Doors','framework'),
				'name' => 'doors',
				'type' => 'text',
				'instructions' => __('Enter the number of doors.','framework'),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5284d03821fab',
				'label' => __('Registration Year','framework'),
				'name' => 'registration_year',
				'type' => 'date_picker',
				'instructions' => __('Month and year of registration / production','framework'),
				'date_format' => 'yy/mm/dd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_5284d114becls',
				'label' => __('Vehicle Classification','framework'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_533c06197105d',
				'label' => __('Select Vehicle Model - Manufacturer','framework'),
				'name' => 'select_vehicle_model_manufacturer',
				'type' => 'taxonomy',
				'taxonomy' => 'vehicle_model',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_533c043c71052',
				'label' => __('Vehicle Type','framework'),
				'name' => 'vehicle_type',
				'type' => 'taxonomy',
				'instructions' => __('Select the vehicle type here.','framework'),
				'required' => 1,
				'taxonomy' => 'vehicle_type',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_533c046871053',
				'label' => __('Vehicle Fuel Type','framework'),
				'name' => 'vehicle_fuel_type',
				'type' => 'taxonomy',
				'instructions' => __('Select the vehicle fuel type.','framework'),
				'required' => 1,
				'taxonomy' => 'vehicle_fuel_type',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_533c04a171054',
				'label' => __('Select Vehicle Color','framework'),
				'name' => 'select_vehicle_color',
				'type' => 'taxonomy',
				'instructions' => __('Select the color of the vehicle.','framework'),
				'taxonomy' => 'vehicle_color',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_533c04f071055',
				'label' => __('Select Vehicle Status','framework'),
				'name' => 'select_vehicle_status',
				'type' => 'taxonomy',
				'instructions' => __('Select the status of the vehicle.','framework'),
				'taxonomy' => 'vehicle_status',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_533c052271056',
				'label' => __('Select Vehicle Gearbox','framework'),
				'name' => 'select_vehicle_gearbox',
				'type' => 'taxonomy',
				'instructions' => __('Select vehicle gearbox','framework'),
				'taxonomy' => 'vehicle_gearbox',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_533c054371057',
				'label' => __('Select Vehicle Interior Features','framework'),
				'name' => 'select_vehicle_interior_features',
				'type' => 'taxonomy',
				'instructions' => __('Select vehicle interior features','framework'),
				'required' => 1,
				'taxonomy' => 'vehicle_interior_feature',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_533c056c71058',
				'label' => __('Select Vehicle Exterior Features','framework'),
				'name' => 'select_vehicle_exterior_features',
				'type' => 'taxonomy',
				'instructions' => __('Select vehicle exterior features','framework'),
				'taxonomy' => 'vehicle_exterior_feature',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_533c058771059',
				'label' => __('Select Vehicle Safety Features','framework'),
				'name' => 'select_vehicle_safety_features',
				'type' => 'taxonomy',
				'instructions' => __('Select vehicle safety features','framework'),
				'taxonomy' => 'vehicle_safety_feature',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_533c05a37105a',
				'label' => __('Select Vehicle Extra Features','framework'),
				'name' => 'select_vehicle_extra_features',
				'type' => 'taxonomy',
				'instructions' => __('Select vehicle extra features','framework'),
				'taxonomy' => 'vehicle_extra',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_533c05d67105b',
				'label' => __('Select Vehicle Location','framework'),
				'name' => 'select_vehicle_location',
				'type' => 'taxonomy',
				'instructions' => __('Select vehicle location','framework'),
				'taxonomy' => 'vehicle_location',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_533c05fd7105c',
				'label' => __('Select Vehicle Age','framework'),
				'name' => 'select_vehicle_age',
				'type' => 'taxonomy',
				'instructions' => __('Select vehicle age','framework'),
				'taxonomy' => 'vehicle_year',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5284d114bea37',
				'label' => __('Vehicle Images','framework'),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5284d3935e6ft',
				'label' => __('Featured Image','framework'),
				'name' => 'vehicle_featured_image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5284d3935e691',
				'label' => __('Additional Image 1','framework'),
				'name' => 'additional_image_1',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5284d3c05e692',
				'label' => __('Additional Image 2','framework'),
				'name' => 'additional_image_2',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5284d3c75e693',
				'label' => __('Additional Image 3','framework'),
				'name' => 'additional_image_3',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5284d3cc5e694',
				'label' => __('Additional Image 4','framework'),
				'name' => 'additional_image_4',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5284d3d25e695',
				'label' => __('Additional Image 5','framework'),
				'name' => 'additional_image_5',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'vehicles',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_vehicle-type-icon',
		'title' => 'Vehicle Type Icon',
		'fields' => array (
			array (
				'key' => 'field_52c5ec3c6336d',
				'label' => 'Vehicle Type Icon',
				'name' => 'vehicle_type_icon',
				'type' => 'image',
				'instructions' => 'Upload an image that will be used as icon for the homepage shortcode module that displays the vehicle types by icon. Please refer to the documentation for more information.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'vehicle_type',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_vehicles-submission-settings',
		'title' => 'Vehicles Submission Settings',
		'fields' => array (
			array (
				'key' => 'field_5297b74a651b5',
				'label' => 'Main Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5297b4f2651b2',
				'label' => 'Account Creation',
				'name' => 'account_creation',
				'type' => 'true_false',
				'instructions' => 'If enabled, non-logged in users will be able to create an account by entering their email address on the auto submission form.',
				'message' => 'Allow account creation',
				'default_value' => 1,
			),
			array (
				'key' => 'field_5297b704651b3',
				'label' => 'Account required',
				'name' => 'account_required',
				'type' => 'true_false',
				'instructions' => 'If disabled, non-logged in users will be able to submit auto listings without creating an account.',
				'message' => 'Vehicle submission requires an account',
				'default_value' => 1,
			),
			array (
				'key' => 'field_5297b72e651b4',
				'label' => 'Approval Required',
				'name' => 'approval_required',
				'type' => 'true_false',
				'instructions' => 'If enabled, new submissions will be inactive, pending admin approval. Note: automatically approved submissions will not expire.',
				'message' => 'New submissions require admin approval',
				'default_value' => 1,
			),
			array (
				'key' => 'field_5297b75d651b6',
				'label' => 'Listing duration',
				'name' => 'listing_duration',
				'type' => 'text',
				'instructions' => 'How many days listings are live before expiring. Can be left blank to never expire.',
				'default_value' => 30,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5297b76e651b7',
				'label' => 'Submit Page',
				'name' => 'submit_page',
				'type' => 'page_link',
				'instructions' => 'Select the the page where you have assigned the "Submit Vehicle" page template. This lets the theme know where the form is located.',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5297c68b1765c',
				'label' => 'Map Center Latitude',
				'name' => 'map_center_latitude',
				'type' => 'text',
				'instructions' => 'Enter the latitude of the address that you wish to use as center of the map when submitting a vehicle.',
				'default_value' => '40.714353',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5297c6ae1765d',
				'label' => 'Map Center Longitude',
				'name' => 'map_center_longitude',
				'type' => 'text',
				'instructions' => 'Enter the longitude of the address that you wish to use as center of the map when submitting a vehicle.',
				'default_value' => '-74.005973',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5297c6d11765e',
				'label' => 'Fields Requirements',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5297c92871203',
				'label' => 'Set Vehicle Features Fields As Required',
				'name' => 'set_vehicle_features_fields_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set this field as required.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297ca5171204',
				'label' => 'Set Mileage As Required',
				'name' => 'set_mileage_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297ca7c71205',
				'label' => 'Set Motor Capacity As Required',
				'name' => 'set_motor_capacity_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297ca9371206',
				'label' => 'Set Motor Power Fields As Required',
				'name' => 'set_motor_power_fields_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297caac71207',
				'label' => 'Set Consumption Field As Required',
				'name' => 'set_consumption_field_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297cac471208',
				'label' => 'Set Emission Class Field As Required',
				'name' => 'set_emission_class_field_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297cad871209',
				'label' => 'Set Doors Field As Required',
				'name' => 'set_doors_field_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297caed7120a',
				'label' => 'Set Registration Date Field As Required',
				'name' => 'set_registration_date_field_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297cb347120b',
				'label' => 'Set Price Discount Field As Required',
				'name' => 'set_price_discount_field_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297cb4a7120c',
				'label' => 'Set Featured Image Field As Required',
				'name' => 'set_featured_image_field_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_5297cb667120d',
				'label' => 'Set Additional Image 1 As Required',
				'name' => 'set_additional_image_1_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297cb787120e',
				'label' => 'Set Additional Image 2 As Required',
				'name' => 'set_additional_image_2_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297cb887120f',
				'label' => 'Set Additional Image 3 As Required',
				'name' => 'set_additional_image_3_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297cb9771210',
				'label' => 'Set Additional Image 4 As Required',
				'name' => 'set_additional_image_4_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297cbaa71211',
				'label' => 'Set Additional Image 5 As Required',
				'name' => 'set_additional_image_5_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5297cbc071212',
				'label' => 'Set Vehicle Address Field As Required',
				'name' => 'set_vehicle_address_field_as_required',
				'type' => 'true_false',
				'instructions' => 'Enable this option to set the field as required',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_52c9431e0469c',
				'label' => 'Email Notifications',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_52c943280469d',
				'label' => 'Vehicle Submission Email',
				'name' => 'vehicle_submission_email_admin',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to send an email notification to the admin of the website when a new vehicle has been submitted.',
				'message' => 'Vehicle Submission Email Admin',
				'default_value' => 1,
			),
			array (
				'key' => 'field_52c943800469f',
				'label' => 'Notification To User',
				'name' => 'notification_to_user',
				'type' => 'true_false',
				'instructions' => 'Send an email notification to the user when a submission has been successfully made.',
				'message' => 'Notification To User',
				'default_value' => 1,
			),
			array (
				'key' => 'field_52c94421046a0',
				'label' => 'Approval Email',
				'name' => 'approval_email',
				'type' => 'true_false',
				'instructions' => 'Send an email notification to the user when one of his vehicles has been successfully published.',
				'message' => 'Approval Email',
				'default_value' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-vehicles-submission',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_vehicles-theme-settings',
		'title' => 'Vehicles Theme Settings',
		'fields' => array (
			array (
				'key' => 'field_5284ed9f267ad',
				'label' => 'General Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5284edab267ae',
				'label' => 'Categories Header Type',
				'name' => 'categories_header_type',
				'type' => 'select',
				'instructions' => 'Select what kind of content you\'d like to display into the header of the vehicles categories. These includes types, fuel type, features and all the other categorization of the vehicles.',
				'choices' => array (
					'Title Only' => 'Category Title Only',
					'Title With Subtitle' => 'Category Title + Description',
				),
				'default_value' => 'Title Only',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5284f165267b0',
				'label' => 'Categories Header Background Color',
				'name' => 'categories_header_background_color',
				'type' => 'color_picker',
				'instructions' => 'Set the color for the header background',
				'default_value' => '#2d3e52',
			),
			array (
				'key' => 'field_5284f079267af',
				'label' => 'Categories Header Overlay Color',
				'name' => 'categories_header_overlay_color',
				'type' => 'color_picker',
				'instructions' => 'Set the color of the overlay for the background of the header.',
				'default_value' => '#2d3e52',
			),
			array (
				'key' => 'field_5284f191267b1',
				'label' => 'Categories Header Background Image',
				'name' => 'categories_header_background_image',
				'type' => 'image',
				'instructions' => 'If needed you can set an image as background for the header.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5284f96eb67e5',
				'label' => 'Categories Layout Settings',
				'name' => 'categories_layout_settings',
				'type' => 'select',
				'instructions' => 'Select the position of the sidebar into the categories pages.',
				'choices' => array (
					'Left Side Sidebar' => 'Left Side Sidebar',
					'Right Side Sidebar' => 'Right Side Sidebar',
					'Fullwidth' => 'Fullwidth',
				),
				'default_value' => 'Right Side Sidebar',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_528522fbef269',
				'label' => 'Vehicles Per Page',
				'name' => 'vehicles_per_page',
				'type' => 'number',
				'instructions' => 'Set the amount of vehicles you\'d like to display per page.',
				'default_value' => 10,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_52852a42b0da6',
				'label' => 'Display Pagination On Top',
				'name' => 'display_pagination_on_top',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to enable the pagination on top of the vehicles as well.',
				'message' => 'Display Pagination On Top',
				'default_value' => 1,
			),
			array (
				'key' => 'field_52852a0ab0da5',
				'label' => 'Display Vehicles View Filter',
				'name' => 'display_vehicles_view_filter',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the vehicle filter.',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_528528402de39',
				'label' => 'Default Vehicles View',
				'name' => 'default_vehicles_view',
				'type' => 'select',
				'instructions' => 'Select the default vehicle view mode. This will be used to display vehicles in your taxonomy pages.',
				'choices' => array (
					'List Mode' => 'List Mode',
					'Grid Mode' => 'Grid Mode',
					'Map Mode' => 'Map Mode',
				),
				'default_value' => 'List Mode',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52a1cf38ca6b6',
				'label' => 'Enable Favorites System',
				'name' => 'enable_favorites_system',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to enable favorites system.',
				'message' => 'Enable Favorites System',
				'default_value' => 1,
			),
			array (
				'key' => 'field_528523a3e1159',
				'label' => 'Vehicle Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_528523d6e115a',
				'label' => 'Vehicle Permalink',
				'name' => 'vehicle_permalink',
				'type' => 'text',
				'instructions' => 'Enter the slug that you\'d like to use as permalink for your vehicles. Remember to refresh your permalinks after changing the slug here. Otherwise you will get a 404 error.',
				'default_value' => 'vehicle',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52852405e115b',
				'label' => 'Currency Code',
				'name' => 'currency_code',
				'type' => 'text',
				'instructions' => 'The name of the currency being used. (i.e. Dollar, Euro, Pound) in singular form.',
				'default_value' => 'USD',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52852478e115c',
				'label' => 'Currency Symbol',
				'name' => 'currency_symbol',
				'type' => 'text',
				'instructions' => 'The symbol of the currency being used. (i.e. $, €, £) in singular form.',
				'default_value' => '$',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52852489e115d',
				'label' => 'Currency Position',
				'name' => 'currency_position',
				'type' => 'select',
				'instructions' => 'The symbol the position from against price: Left / Right',
				'choices' => array (
					'Left' => 'Left',
					'Right' => 'Right',
				),
				'default_value' => 'Left',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_528524a4919c3',
				'label' => 'Mileage symbol',
				'name' => 'mileage_symbol',
				'type' => 'text',
				'instructions' => 'Mileage symbol (i.e. KM, MI)',
				'default_value' => 'KM',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_528524c4919c4',
				'label' => 'Consumption symbol',
				'name' => 'consumption_symbol',
				'type' => 'text',
				'instructions' => 'Input consumption symbol',
				'default_value' => 'MPG',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5288a11ad03ef',
				'label' => 'Display Vehicle Position Address',
				'name' => 'display_vehicle_position_address',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the vehicle address in taxonomies.',
				'message' => 'Display Vehicle Position Address',
				'default_value' => 1,
			),
			array (
				'key' => 'field_5288a29c51a2b',
				'label' => 'Display Mileage In Taxonomy List',
				'name' => 'display_mileage_in_taxonomy_list',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display mileage into the taxonomies pages.',
				'message' => 'Display Mileage In Taxonomy List',
				'default_value' => 1,
			),
			array (
				'key' => 'field_5288a4287f393',
				'label' => 'Display Registration Year In Taxonomy List',
				'name' => 'display_registration_year_in_taxonomy_list',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display registration date into taxonomy list.',
				'message' => 'Display Registration Year In Taxonomy List',
				'default_value' => 1,
			),
			array (
				'key' => 'field_52852a6eb0da7',
				'label' => 'Map View Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_528920b6b416d',
				'label' => 'Enable Map system',
				'name' => 'enable_map_system',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to enable the display of the map when filtering vehicles.',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_52892052b416b',
				'label' => 'Map Center Point Address',
				'name' => 'map_center_point',
				'type' => 'text',
				'instructions' => 'Enter the address that will be used as center of the map.',
				'default_value' => 'London United Kingdom',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52892076b416c',
				'label' => 'Marker Custom Image',
				'name' => 'marker_custom_image',
				'type' => 'image',
				'instructions' => 'Upload A Custom Marker for your vehicles when viewed on the map. Leave blank if not needed.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_52893d35c7a2d',
				'label' => 'Featured Vehicle Marker',
				'name' => 'featured_vehicle_marker',
				'type' => 'image',
				'instructions' => 'Here you can set an alternative marker for featured vehicles.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_528920b6b416d',
				'label' => 'Enable Geolocation?',
				'name' => 'enable_geolocation',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to enable geolocation on the map. This will allow the map to display the current position of the user.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_528b3c46d2eea',
				'label' => 'Single Vehicle Page',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_528b3c54d2eeb',
				'label' => 'Display Vehicle Address',
				'name' => 'display_vehicle_address',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the vehicle address below the price.',
				'message' => 'Display Vehicle Address',
				'default_value' => 1,
			),
			array (
				'key' => 'field_528b3cafd2eec',
				'label' => 'Vehicle Details ',
				'name' => 'vehicle_details',
				'type' => 'checkbox',
				'instructions' => 'Select the details that you wish to display into the single vehicle page.',
				'choices' => array (
					'Display Model Type' => 'Display Model Type',
					'Display Registration Year' => 'Display Registration Year',
					'Display Fuel Type' => 'Display Fuel Type',
					'Display Engine Details' => 'Display Engine Details',
					'Display Transmission' => 'Display Transmission',
					'Display Color' => 'Display Color',
					'Display Doors' => 'Display Doors',
					'Display Emissions' => 'Display Emissions',
					'Display Location' => 'Display Location',
					'Display Mileage' => 'Display Mileage',
					'Display Featured Mark' => 'Display Featured Mark',
				),
				'default_value' => 'Display Model Type
	Display Registration Year
	Display Fuel Type
	Display Engine Details
	Display Transmission
	Display Color
	Display Doors
	Display Emissions
	Display Location
	Display Mileage
	Display Featured Mark',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_528b654c97e61',
				'label' => 'Single Vehicle Layout',
				'name' => 'single_vehicle_layout',
				'type' => 'select',
				'instructions' => 'Select the position of the sidebar into the single pages.',
				'choices' => array (
					'Left Side Sidebar' => 'Left Side Sidebar',
					'Right Side Sidebar' => 'Right Side Sidebar',
					'Fullwidth' => 'Fullwidth',
				),
				'default_value' => 'Right Side Sidebar',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_528b8497db4d2',
				'label' => 'Vehicle Features',
				'name' => 'vehicle_features',
				'type' => 'checkbox',
				'instructions' => 'Enable or disable the elements that you\'d like to display.',
				'choices' => array (
					'Display Exterior & Interior Features' => 'Display Exterior & Interior Features',
					'Display Safety & Extra Features' => 'Display Safety & Extra Features',
					'Display Contact Dealer' => 'Display Contact Dealer',
				),
				'default_value' => 'Display Exterior & Interior Features
	Display Safety & Extra Features
	Display Contact Dealer',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_528b85a419aea',
				'label' => 'Disable vehicle features display',
				'name' => 'disable_vehicle_features_display',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to completely disable the features tabs.',
				'message' => 'Disable vehicle features display',
				'default_value' => 0,
			),
			array (
				'key' => 'field_528ba21bfcfb7',
				'label' => 'Custom Top Content',
				'name' => 'custom_top_content',
				'type' => 'wysiwyg',
				'instructions' => 'Here you can add content that will be displayed on top of vehicle overview (above the gallery and information) into each vehicle page. This is useful if you wish to add ads or any other kind of content.',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_528ba2a5fcfb8',
				'label' => 'Custom Bottom Content',
				'name' => 'custom_bottom_content',
				'type' => 'wysiwyg',
				'instructions' => 'Here you can add content that will be displayed at the bottom of each vehicle page just above the footer. This is useful if you wish to add ads or any other kind of content.',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_528bd68d85142',
				'label' => 'Display Brands Carousel',
				'name' => 'display_brands_carousel',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the brands carousel into the single listings pages.',
				'message' => 'Display Brands Carousel',
				'default_value' => 1,
			),
			array (
				'key' => 'field_528ba459f99e9',
				'label' => 'Display Latest Vehicle Carousel',
				'name' => 'display_latest_vehicle_carousel',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display a vehicle carousel at the bottom of each single vehicle page.',
				'message' => 'Display Latest Vehicle Carousel',
				'default_value' => 1,
			),
			array (
				'key' => 'field_528ba490f99ea',
				'label' => 'Display Featured Vehicle Carousel',
				'name' => 'display_featured_vehicle_carousel',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display a featured vehicles carousel at the bottom of each page.',
				'message' => 'Display Featured Vehicle Carousel',
				'default_value' => 0,
			),
			array (
				'key' => 'field_528bb03235540',
				'label' => 'Limit Items In Carousel',
				'name' => 'limit_items_in_carousel',
				'type' => 'number',
				'instructions' => 'Enter the amount of vehicles you want to display into the carousel.',
				'default_value' => 15,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_528bb5a008ef1',
				'label' => 'Display Signup Message',
				'name' => 'display_signup_message',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the signup message into the carousel.',
				'message' => 'Display Signup Message',
				'default_value' => 1,
			),
			array (
				'key' => 'field_528bb88d361f2',
				'label' => 'Set Background Picture For Carousel',
				'name' => 'set_background_picture_for_carousel',
				'type' => 'image',
				'instructions' => 'If needed you can set a background image for the carousel.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_528bbc975a20e',
				'label' => 'Set Background Image Overlay Color',
				'name' => 'set_background_image_overlay_color',
				'type' => 'color_picker',
				'instructions' => 'Set the overlay color if you added a background image.',
				'default_value' => '#2d3e52',
			),
			array (
				'key' => 'field_52b55c49b7beb',
				'label' => 'Featured Vehicles',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_52b55c55b7bec',
				'label' => 'Display Featured Vehicle Information Bar',
				'name' => 'display_featured_vehicle_information_bar',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the dealer information underneath the featured vehicle information.',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_52b55c81b7bed',
				'label' => 'Display Featured Vehicle Date',
				'name' => 'display_featured_vehicle_date',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the featured vehicle date',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_52b55c9db7bee',
				'label' => 'Display Featured Vehicle Dealer Wesite',
				'name' => 'display_featured_vehicle_dealer_website',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the dealer website.',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_52b55cbfb7bef',
				'label' => 'Display Featured Vehicle Dealer Name',
				'name' => 'display_featured_vehicle_dealer_name',
				'type' => 'true_false',
				'instructions' => 'Enable this option if you wish to display the dealer name',
				'message' => '',
				'default_value' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-vehicles-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_inner-page-options',
		'title' => 'Inner Page Options',
		'fields' => array (
			array (
				'key' => 'field_526958657ae24',
				'label' => 'Page Header Content Type',
				'name' => 'page_header_content_type',
				'type' => 'radio',
				'instructions' => 'Select the content type of the page header.',
				'choices' => array (
					'Title Only' => 'Title Only',
					'Title With Subtitle' => 'Title With Subtitle',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'Title Only',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_526958c47ae25',
				'label' => 'Subtitle',
				'name' => 'subtitle',
				'type' => 'text',
				'instructions' => 'Enter the subtitle of the page',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_526958657ae24',
							'operator' => '==',
							'value' => 'Title With Subtitle',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52695968466ca',
				'label' => 'Background Color',
				'name' => 'header_background_color',
				'type' => 'color_picker',
				'instructions' => 'Select the color of the page header background',
				'default_value' => '#1A86CA',
			),
			array (
				'key' => 'field_526959ae6f16a',
				'label' => 'Background Image',
				'name' => 'header_background_image',
				'type' => 'image',
				'instructions' => 'If you wish to display an image you can upload it here.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_52695a316f16c',
				'label' => 'Overlay Color',
				'name' => 'overlay_color',
				'type' => 'color_picker',
				'instructions' => 'Set the color of the overlay.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_526958657ae24',
							'operator' => '==',
							'value' => 'Title Only',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '#1A86CA',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'page_template',
					'operator' => '!=',
					'value' => 'templates/template-homepage.php',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
}